name: Security Pipeline

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: make install

      - name: Run security scan
        run: make security-scan
